### ISSUE TITLE
After using ffmpeg6.0_nvmpi.patch, ffmpeg 6.0 version make encountered undefined types

### ISSUE THREAD

**Issue by Strange-mzi** [Keylost/jetson-ffmpeg#30]
**Hey @Keylost.**

I am encountering compilation errors when building FFmpeg with NVENC support. I have followed the standard build process, but I am getting several errors related to missing members in the `NV_ENC_CONFIG_HEVC `and `NV_ENC_CONFIG_AV1 `structures, as well as undeclared buffer format constants.

**Here are the details:**
**Environment**:

- OS: Ubuntu 20.04

- Platform Module : NVIDIA Jetson Xavier NX

- FFmpeg version: [6.0]

**Error Messages:**

![image](https://github.com/user-attachments/assets/205d30d5-2102-4249-9799-b4e9ab9a9ce6)

     

**Additional Information:**

- I have ensured that the pthread library is installed and correctly linked.

- I have tried updating both FFmpeg and the NVENC SDK to their latest versions, but the issue persists.

Thank you for your help!

Best regards,
Strange.

**Comment by Keylost** [comment]
Hi!
ffmpeg6.0_nvmpi.patch does not affect the compilation of nvenc.c.
The patch adds support for nvmpi, but not nvenc.
Try configuring ffmpeg with the --disable-nvenc parameter.
P.S. Nvenc is designed to work with discrete NVIDIA graphics cards. Nvenc will not work on Jetson platforms, that's why we made nvmpi.
